// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/factory.proto

package factory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type BoolValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{1}
}

func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type StringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{2}
}

func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (m *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(m, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BoxSpecification struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Depth                int32    `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxSpecification) Reset()         { *m = BoxSpecification{} }
func (m *BoxSpecification) String() string { return proto.CompactTextString(m) }
func (*BoxSpecification) ProtoMessage()    {}
func (*BoxSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{3}
}

func (m *BoxSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxSpecification.Unmarshal(m, b)
}
func (m *BoxSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxSpecification.Marshal(b, m, deterministic)
}
func (m *BoxSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxSpecification.Merge(m, src)
}
func (m *BoxSpecification) XXX_Size() int {
	return xxx_messageInfo_BoxSpecification.Size(m)
}
func (m *BoxSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_BoxSpecification proto.InternalMessageInfo

func (m *BoxSpecification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoxSpecification) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BoxSpecification) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *BoxSpecification) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type Boxes struct {
	Boxes                []*BoxSpecification `protobuf:"bytes,1,rep,name=Boxes,proto3" json:"Boxes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Boxes) Reset()         { *m = Boxes{} }
func (m *Boxes) String() string { return proto.CompactTextString(m) }
func (*Boxes) ProtoMessage()    {}
func (*Boxes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{4}
}

func (m *Boxes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boxes.Unmarshal(m, b)
}
func (m *Boxes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boxes.Marshal(b, m, deterministic)
}
func (m *Boxes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boxes.Merge(m, src)
}
func (m *Boxes) XXX_Size() int {
	return xxx_messageInfo_Boxes.Size(m)
}
func (m *Boxes) XXX_DiscardUnknown() {
	xxx_messageInfo_Boxes.DiscardUnknown(m)
}

var xxx_messageInfo_Boxes proto.InternalMessageInfo

func (m *Boxes) GetBoxes() []*BoxSpecification {
	if m != nil {
		return m.Boxes
	}
	return nil
}

type StatusMessage struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusMessage) Reset()         { *m = StatusMessage{} }
func (m *StatusMessage) String() string { return proto.CompactTextString(m) }
func (*StatusMessage) ProtoMessage()    {}
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbbe5d11a86906e, []int{5}
}

func (m *StatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMessage.Unmarshal(m, b)
}
func (m *StatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMessage.Marshal(b, m, deterministic)
}
func (m *StatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMessage.Merge(m, src)
}
func (m *StatusMessage) XXX_Size() int {
	return xxx_messageInfo_StatusMessage.Size(m)
}
func (m *StatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMessage proto.InternalMessageInfo

func (m *StatusMessage) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *StatusMessage) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*BoolValue)(nil), "BoolValue")
	proto.RegisterType((*StringValue)(nil), "StringValue")
	proto.RegisterType((*BoxSpecification)(nil), "BoxSpecification")
	proto.RegisterType((*Boxes)(nil), "Boxes")
	proto.RegisterType((*StatusMessage)(nil), "StatusMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoxFactoryClient is the client API for BoxFactory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoxFactoryClient interface {
	MakeBox(ctx context.Context, in *BoxSpecification, opts ...grpc.CallOption) (*Empty, error)
	GetBoxes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Boxes, error)
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusMessage, error)
}

type boxFactoryClient struct {
	cc *grpc.ClientConn
}

func NewBoxFactoryClient(cc *grpc.ClientConn) BoxFactoryClient {
	return &boxFactoryClient{cc}
}

func (c *boxFactoryClient) MakeBox(ctx context.Context, in *BoxSpecification, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/BoxFactory/MakeBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxFactoryClient) GetBoxes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Boxes, error) {
	out := new(Boxes)
	err := c.cc.Invoke(ctx, "/BoxFactory/GetBoxes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxFactoryClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusMessage, error) {
	out := new(StatusMessage)
	err := c.cc.Invoke(ctx, "/BoxFactory/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxFactoryServer is the server API for BoxFactory service.
type BoxFactoryServer interface {
	MakeBox(context.Context, *BoxSpecification) (*Empty, error)
	GetBoxes(context.Context, *Empty) (*Boxes, error)
	Status(context.Context, *Empty) (*StatusMessage, error)
}

func RegisterBoxFactoryServer(s *grpc.Server, srv BoxFactoryServer) {
	s.RegisterService(&_BoxFactory_serviceDesc, srv)
}

func _BoxFactory_MakeBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoxSpecification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxFactoryServer).MakeBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoxFactory/MakeBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxFactoryServer).MakeBox(ctx, req.(*BoxSpecification))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxFactory_GetBoxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxFactoryServer).GetBoxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoxFactory/GetBoxes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxFactoryServer).GetBoxes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxFactory_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxFactoryServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoxFactory/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxFactoryServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoxFactory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BoxFactory",
	HandlerType: (*BoxFactoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeBox",
			Handler:    _BoxFactory_MakeBox_Handler,
		},
		{
			MethodName: "GetBoxes",
			Handler:    _BoxFactory_GetBoxes_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _BoxFactory_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/factory.proto",
}

func init() { proto.RegisterFile("proto/factory.proto", fileDescriptor_9bbbe5d11a86906e) }

var fileDescriptor_9bbbe5d11a86906e = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4b, 0x6e, 0xe2, 0x40,
	0x10, 0x95, 0x0d, 0x36, 0x50, 0x66, 0xd0, 0xd0, 0x83, 0x46, 0x16, 0x9a, 0x85, 0xc7, 0xb3, 0x18,
	0x36, 0xd8, 0x09, 0xc9, 0x2a, 0xbb, 0x58, 0x4a, 0xb2, 0x22, 0x0b, 0x23, 0x65, 0xdf, 0x98, 0xc6,
	0xee, 0x18, 0x5c, 0x96, 0xdd, 0x10, 0xb3, 0xcd, 0x15, 0x72, 0x8e, 0x9c, 0x26, 0x57, 0xc8, 0x41,
	0x22, 0x77, 0x43, 0xfe, 0xbb, 0x7a, 0xaf, 0xde, 0xeb, 0x7a, 0x55, 0x0d, 0xbf, 0xf2, 0x02, 0x05,
	0xfa, 0x4b, 0x1a, 0x09, 0x2c, 0x76, 0x9e, 0x44, 0xc3, 0x3f, 0x31, 0x62, 0xbc, 0x62, 0x3e, 0xcd,
	0xb9, 0x4f, 0xb3, 0x0c, 0x05, 0x15, 0x1c, 0xb3, 0x52, 0x75, 0xdd, 0x16, 0x18, 0x17, 0xeb, 0x5c,
	0xec, 0xdc, 0xbf, 0xd0, 0x09, 0x10, 0x57, 0x37, 0x74, 0xb5, 0x61, 0x64, 0x00, 0xc6, 0xb6, 0x2e,
	0x6c, 0xcd, 0xd1, 0x46, 0xed, 0x50, 0x01, 0xf7, 0x1f, 0x58, 0x33, 0x51, 0xf0, 0x2c, 0xfe, 0x46,
	0xd4, 0x39, 0x88, 0x6e, 0xe1, 0x67, 0x80, 0xd5, 0x2c, 0x67, 0x11, 0x5f, 0xf2, 0x48, 0xce, 0x22,
	0x04, 0x9a, 0x19, 0x5d, 0x1f, 0x84, 0xb2, 0x26, 0xbf, 0xc1, 0x4c, 0x18, 0x8f, 0x13, 0x61, 0xeb,
	0x8e, 0x36, 0x32, 0xc2, 0x3d, 0xaa, 0x5f, 0xbd, 0xe3, 0x0b, 0x91, 0xd8, 0x0d, 0x49, 0x2b, 0x50,
	0xb3, 0x0b, 0x96, 0x8b, 0xc4, 0x6e, 0x2a, 0x56, 0x02, 0xf7, 0x08, 0x8c, 0x00, 0x2b, 0x56, 0x92,
	0xff, 0xfb, 0xc2, 0xd6, 0x9c, 0xc6, 0xc8, 0x9a, 0xf4, 0xbd, 0xcf, 0x11, 0x42, 0xd5, 0x77, 0xcf,
	0xe1, 0xc7, 0x4c, 0x50, 0xb1, 0x29, 0xa7, 0xac, 0x2c, 0x69, 0xcc, 0x88, 0x03, 0x56, 0xc9, 0x8a,
	0x2d, 0x8f, 0xd8, 0xf5, 0x5b, 0xc2, 0xf7, 0x14, 0xe9, 0x81, 0x8e, 0xa9, 0x0c, 0xd9, 0x0e, 0x75,
	0x4c, 0x27, 0x8f, 0x1a, 0x40, 0x80, 0xd5, 0xa5, 0x3a, 0x32, 0x39, 0x83, 0xd6, 0x94, 0xa6, 0x2c,
	0xc0, 0x8a, 0x7c, 0x1d, 0x3b, 0x34, 0x3d, 0x75, 0xdd, 0xc1, 0xfd, 0xd3, 0xf3, 0x83, 0xde, 0x73,
	0xbb, 0xfe, 0xf6, 0xd8, 0x5f, 0xd3, 0x94, 0x8d, 0xe7, 0x58, 0x91, 0x31, 0xb4, 0xaf, 0x98, 0x50,
	0x2b, 0xec, 0x95, 0x43, 0xd3, 0x53, 0x49, 0xfb, 0xd2, 0x61, 0x91, 0x4e, 0xed, 0x98, 0x4b, 0xc9,
	0x29, 0x98, 0x2a, 0xfc, 0xab, 0xb8, 0xe7, 0x7d, 0xd8, 0xc6, 0x25, 0xd2, 0xd4, 0x25, 0x50, 0x9b,
	0x4a, 0xd9, 0x9a, 0x9b, 0xf2, 0xa3, 0x4f, 0x5e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x5e, 0x7a,
	0x8b, 0x1d, 0x02, 0x00, 0x00,
}
